# DB ?? ??
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name:
    # driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:mariadb://127.0.0.1:3306/mybatis?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: lldj
    password: lldj123414
## MyBatis ?? ??
#mybatis:
#  mapper-locations: mybatis-mapper/*.xml
#  type-aliases-package: com.ay.study.mybatis_1101.app.article.dto